export const institutions = [
  {
    id: 1,
    category: 'Centre de excelenţă',
    name: 'I. P. Centrul de excelenţă în informatică şi tehnologii informaţionale din Chișinău',
    founding_authority: 'Ministerul Educației și Cercetării',
    institution_specialization: 'Domeniul TIC',
    physical_address: 'mun. Chişinău, str. Sarmizegetusa, nr. 48',
    url: 'https://www.ceiti.md/',
    email: 'secretariat@ceiti.md',
    contact_phone: '022 523 001',
    coordinates: [47.0105, 28.8638]
  },
  {
    id: 2,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în construcţii din Bălţi',
    founding_authority: 'Ministerul Educației și Cercetării',
    institution_specialization: 'Construcţii',
    physical_address: 'mun. Bălţi, str. Independenţei, nr. 25',
    url: 'https://www.cecb.md/',
    email: 'contact@cecb.md',
    contact_phone: '023 456 789',
    coordinates: [47.7532, 27.9289]
  },
  {
    id: 3,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în agricultură din Orhei',
    founding_authority: 'Ministerul Agriculturii',
    institution_specialization: 'Agricultură',
    physical_address: 'Orhei, str. Mihai Viteazu, nr. 10',
    url: 'https://www.ceao.md/',
    email: 'info@ceao.md',
    contact_phone: '023 123 456',
    coordinates: [47.3817, 28.8235]
  },
  {
    id: 4,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în medicină din Cahul',
    founding_authority: 'Ministerul Sănătății',
    institution_specialization: 'Medicină',
    physical_address: 'Cahul, str. Ștefan cel Mare, nr. 50',
    url: 'https://www.cemc.md/',
    email: 'admin@cemc.md',
    contact_phone: '029 654 321',
    coordinates: [45.9066, 28.1947]
  },
  {
    id: 5,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în arte din Comrat',
    founding_authority: 'Ministerul Culturii',
    institution_specialization: 'Arte',
    physical_address: 'Comrat, str. Mateevici, nr. 9',
    url: 'https://www.ceac.md/',
    email: 'arts@ceac.md',
    contact_phone: '027 876 543',
    coordinates: [46.2976, 28.6599]
  },
  {
    id: 6,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în economie din Tiraspol',
    founding_authority: 'Ministerul Economiei',
    institution_specialization: 'Economie',
    physical_address: 'Tiraspol, str. Lenin, nr. 3',
    url: 'https://www.ceet.md/',
    email: 'economy@ceet.md',
    contact_phone: '024 654 987',
    coordinates: [46.8416, 29.6308]
  },
  {
    id: 7,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în turism din Soroca',
    founding_authority: 'Ministerul Turismului',
    institution_specialization: 'Turism',
    physical_address: 'Soroca, str. Cetății, nr. 7',
    url: 'https://www.cet.md/',
    email: 'tourism@cet.md',
    contact_phone: '026 234 567',
    coordinates: [48.1574, 28.2975]
  },
  {
    id: 8,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în științe exacte din Edineț',
    founding_authority: 'Ministerul Științei',
    institution_specialization: 'Științe exacte',
    physical_address: 'Edineț, str. Universității, nr. 1',
    url: 'https://www.cese.md/',
    email: 'science@cese.md',
    contact_phone: '025 345 678',
    coordinates: [48.1726, 27.3035]
  },
  {
    id: 9,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în tehnologii alimentare din Ungheni',
    founding_authority: 'Ministerul Agriculturii',
    institution_specialization: 'Tehnologii alimentare',
    physical_address: 'Ungheni, str. Gheorghe Asachi, nr. 15',
    url: 'https://www.ceta.md/',
    email: 'foodtech@ceta.md',
    contact_phone: '027 123 890',
    coordinates: [47.2067, 27.798]
  },
  {
    id: 10,
    category: 'Centre de excelenţă',
    name: 'Centrul de excelenţă în protecţia mediului din Călărași',
    founding_authority: 'Ministerul Mediului',
    institution_specialization: 'Protecția Mediului',
    physical_address: 'Călărași, str. Pădurilor, nr. 20',
    url: 'https://www.cepm.md/',
    email: 'eco@cepm.md',
    contact_phone: '028 765 432',
    coordinates: [47.2547, 28.3109]
  }
]
